#!/usr/bin/bash
KHUUSAGE="Usage: myss_lab2_2 group";
[[ ! "$#" -eq 1 ]] && { echo $KHUUSAGE; exit 1; }
GROUP_ID=$(getent group "$1" | awk -F: "{print \$3} ")
SECONDARY=$(getent group | awk -F: " {if (\$1 == \"$1\") print \$4} ")
PRIMARY=$(getent passwd | awk -F: "{if (\$4 == \"$GROUP_ID\") print \$1} ")
echo "$SECONDARY $PRIMARY" | gawk -F[\ ,] 'BEGIN {ORS="\n"} {for (i=1;i<=NF;i++) if (h[$i]==0) {h[$i]=1; print $i}}' | sort
