#!/usr/bin/bash
KHUUSAGE="Usage: 
myss_username lab3";
[[ ! $# -eq 1 || ! "$(getent passwd | awk -F: "{if (\$1 == \"$1\") print \$1}" )" = "$1" ]] && { echo $KHUUSAGE; exit 1; }
for DIR in * 
do
        if [[ -d "$DIR" && ! -L "$DIR" ]]
	then
		[[ "$(ls -ldb -- "$DIR" | awk '{print $3}')" = "$1" ]] && { [[ $(ls -ldb -- "$DIR" | cut -c 4) = x ]] && echo "$DIR"; continue; }
                [[ -n "$(groups "$1" | grep -w $(ls -ldb -- "$DIR" | awk '{print $4}'))" ]] && { [[ $(ls -ldb -- "$DIR" | cut -c 7) = x ]] && echo "$DIR"; continue; }
                [[ $(ls -ldb -- "$DIR" | cut -c 10) = x ]] && { echo "$DIR"; continue; }
        fi
done
